authentification_inscription:
    path:     /
    defaults: { _controller: AuthentificationBundle:Authentification:inscription}

authentification_connexion:
    path:     /connexion
    defaults: { _controller: AuthentificationBundle:Authentification:connexion}
